### PR TITLE
Feat231/submitted files

### LINKED ISSUE #231: Implement a gadget to list submitted files in an ILS

### PR DESCRIPTION
**Pull request by davidsandoz**
The submitted files gadget + few changes in online users gadget and time spent gadget. Closes #231 

Doesn't work correctly with ILS yet. When using the drop file gadget to upload a file, the actions sent through activitystreams place a Graasp user (owner of the ILS) as actor of the action instead of the ILS user.

@voz @Wissam-Halimi Should we merge already or wait for a fix with the action logging of the drop file gadget? If we want to merge, could you please review?

### CODE REVIEW

**Comment by Wissam-Halimi** [comment]
@davidsandoz can you please pass by when you have time? we can discuss how to fix the problem you have with ILS contexts. There is already a solution but it's easier if we speak f2f

**Comment by davidsandoz** [comment]
@Wissam-Halimi I met @voz yesterday to discuss about the next semester project and @MJRodriguezTriana was also there and she said that she was going to look to fix the problem. But if it is needed, I can pass by tomorrow at any time.

**Comment by Wissam-Halimi** [comment]
okay, then it looks like there is an overlap here. i will let you figure it out with them, and let me know if there is smth needed.

**Comment by voz** [comment]
@davidsandoz please squash, will merge

**Comment by voz** [comment]
We need it for evaluation tomorrow with teachers

**Comment by davidsandoz** [comment]
@voz Done.

**Comment by MJRodriguezTriana** [comment]
Thank you @davidsandoz !

On 26 Jan 2015, at 16:11, David Sandoz <notifications@github.com<mailto:notifications@github.com>> wrote:


@voz<https://github.com/voz> Done.

**Pull request merged**
